global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nodejs-backend'
    static_configs:
      - targets: ['backend:3000']

  - job_name: 'mysql-db'
    static_configs:
      - targets: ['mysqld-exporter:9104']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
