apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-project
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-username/lab-2.git'
    targetRevision: main
    path: helm/lab-project
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 