apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-maintenance
  namespace: lab-project
  labels:
    app: daily-maintenance
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3 
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: maintenance
            image: busybox:latest
            command:
            - /bin/sh
            - -c
            - |
              echo "Starting daily maintenance at $(date)"
              
              echo "Performing database maintenance..."

              echo "Cleaning up old logs..."

              echo "Performing health checks..."
              if wget -q --spider http://backend:80/health; then
                echo "Backend health check: OK"
              else
                echo "Backend health check: FAILED"
              fi
              
              if wget -q --spider http://prometheus:9090/-/healthy; then
                echo "Prometheus health check: OK"
              else
                echo "Prometheus health check: FAILED"
              fi
              
              if wget -q --spider http://grafana:3000/api/health; then
                echo "Grafana health check: OK"
              else
                echo "Grafana health check: FAILED"
              fi
              
              echo "Daily maintenance completed at $(date)"
            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "128Mi"
                cpu: "100m"
          restartPolicy: OnFailure
          serviceAccountName: default 