apiVersion: v1
data:
  mysql-database: bGFiX2Ri
  mysql-root-password: eW91ci1teXNxbC1wYXNzd29yZA==
  mysql-user: cm9vdA==
kind: Secret
metadata:
  creationTimestamp: null
  name: mysql-secret
  namespace: lab-project
