apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: lab-project
data:
  index.html: |
    <html>
      <head><title>Welcome to NGINX on lab-project!</title></head>
      <body>
        <h1>Hello from NGINX in your lab-project!</h1>
        <p>This is served from a ConfigMap.</p>
      </body>
    </html> 