apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lab-project.fullname" . }}-backend
  labels:
    app: {{ include "lab-project.name" . }}
    component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "lab-project.name" . }}
      component: backend
  template:
    metadata:
      labels:
        app: {{ include "lab-project.name" . }}
        component: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          env:
            {{- toYaml .Values.backend.env | nindent 12 }}
          ports:
            - containerPort: 3000
          livenessProbe:
            {{- toYaml .Values.backend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.backend.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }} 