apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lab-project.fullname" . }}-frontend
  labels:
    app: {{ include "lab-project.name" . }}
    component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "lab-project.name" . }}
      component: frontend
  template:
    metadata:
      labels:
        app: {{ include "lab-project.name" . }}
        component: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 80
          livenessProbe:
            {{- toYaml .Values.frontend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.frontend.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }} 