apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.auth.existingSecret }}
  labels:
    app: {{ include "lab-project.name" . }}
    component: mysql
  annotations:
    "helm.sh/resource-policy": keep
    # Prevents deletion on helm uninstall
stringData:
  rootPassword: {{ .Values.mysql.auth.rootPassword | quote }}
  username: {{ .Values.mysql.auth.username | quote }}
  password: {{ .Values.mysql.auth.password | quote }} 