apiVersion: v1
kind: Service
metadata:
  name: {{ include "lab-project.fullname" . }}-backend
  labels:
    app: {{ include "lab-project.name" . }}
    component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "lab-project.name" . }}
    component: backend 