apiVersion: v1
kind: Service
metadata:
  name: {{ include "lab-project.fullname" . }}-frontend
  labels:
    app: {{ include "lab-project.name" . }}
    component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "lab-project.name" . }}
    component: frontend 