config:
  target: 'http://localhost:3000'
  phases:
    - duration: 60
      arrivalRate: 10
      name: "Warm up"
    - duration: 120
      arrivalRate: 50
      name: "Normal load"
    - duration: 60
      arrivalRate: 100
      name: "Peak load"
    - duration: 60
      arrivalRate: 10
      name: "Cool down"
  defaults:
    headers:
      Content-Type: 'application/json'
      User-Agent: 'Artillery Load Test'

scenarios:
  - name: "API Health Check"
    weight: 20
    flow:
      - get:
          url: "/health"
          expect:
            - statusCode: 200
            - contentType: json

  - name: "User Registration"
    weight: 15
    flow:
      - post:
          url: "/api/users"
          json:
            username: "{{ $randomString() }}"
            email: "{{ $randomString() }}@example.com"
            password: "password123"
          expect:
            - statusCode: [200, 201]
            - contentType: json

  - name: "User Login"
    weight: 25
    flow:
      - post:
          url: "/api/auth/login"
          json:
            username: "testuser"
            password: "password123"
          expect:
            - statusCode: 200
            - contentType: json
            - hasProperty: "token"

  - name: "Get User Profile"
    weight: 20
    flow:
      - get:
          url: "/api/users/profile"
          headers:
            Authorization: "Bearer {{ $randomString() }}"
          expect:
            - statusCode: [200, 401]

  - name: "Database Operations"
    weight: 20
    flow:
      - get:
          url: "/api/data"
          expect:
            - statusCode: 200
            - contentType: json 