name: Enterprise CI/CD Pipeline - Kubernetes

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-to-staging:
    if: ${{ secrets.KUBE_CLUSTER_CONFIGURED == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to staging
        run: |
          helm upgrade --install lab-project-staging ./helm/lab-project
          # ... existing deploy command ... 